name: CI-CD

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # check if everything works first
  tests:
    uses: ./.github/workflows/tests.yml

  # make a new version next, release or prerelease
  release:
    needs: [tests]
    uses: ./.github/workflows/release.yml
