name: Release

# Controls when the action will run.
on:
  workflow_call:

jobs:
  # make a new version first, release or prerelease
  release:
    # Only run this job if new work is pushed to "main"
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:

      - name: Checking out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for semantic-release
          ref: main

      - name: Setup git user
        shell: sh
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Determine the next version number
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: sh
        run: |
          set -x
          python -m pip install python-semantic-release
          NEWVER=$(semantic-release -c semantic-release.toml version --print)
          # version number updates with regexp which is not supported by
          # semantic_release.version_variables in pyproject.toml
          sed -i -e "s/v\([0-9]\+\.\)\{3\}/v$NEWVER./" README.md
          git add README.md
          # creates a release only if there are relevant changes/commits starting with 'fix/feat()'
          semantic-release -c semantic-release.toml version
